//*PUT http://localhost:8081/CurrencyExchange/currencies/1
//Content-Type: application/json

//{
//  "code": "USD",
//  "fullName": "United States Dollar",
// "sign": "$"
//}

DELETE http://localhost:8081/CurrencyExchange/currencies/3
//GET http://localhost:8081/CurrencyExchange/currencies